[package]
name = "gacha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
dotenv = "0.15.0"
rand = "0.8.5"
serde = "1.0.159"
serde_derive = "1.0.159"
